services:
  db:
    image: postgres:18
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    command: ["postgres",
      "-c", "config_file=/etc/postgresql/postgresql.conf",
      "-c", "hba_file=/etc/postgresql/pg_hba.conf"
      ]
    volumes:
      - pgdata:/var/lib/postgresql # persistent storage for database data
      - ./init_db:/docker-entrypoint-initdb.d:ro # initial .sql and .sh executions
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf:ro # custom postgresql.conf
      - ./configs/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro # custom pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - sandbox_user_password
      - postgres_password

secrets:
  postgres_password:
    file: ./.secrets/postgres_password.txt
  sandbox_user_password:
    file: ./.secrets/sandbox_user_password.txt

volumes:
  pgdata: